<a href="https://colab.research.google.com/github/WillyKitheka/code-doyen/blob/main/extracting_assets_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

sample_space_file = pd.read_csv('/content/drive/MyDrive/maGiK_15_sample_space/df_magik15_file1_concat.csv')

In [2]:
sample_space_file

,Unnamed: 0,pick_0,pick_1,pick_2,pick_3,pick_4,pick_5,pick_6,pick_7,pick_8,...,pick_1594313,pick_1594314,pick_1594315,pick_1594316,pick_1594317,pick_1594318,pick_1594319,pick_1594320,pick_1594321,pick_1594322
0,match_0,H,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
1,match_1,H,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
2,match_2,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
3,match_3,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
4,match_4,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
5,match_5,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
6,match_6,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
7,match_7,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
8,match_8,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
9,match_9,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
10,match_10,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
11,match_11,H,H,H,H,H,H,H,H,H,...,A,A,A,A,A,A,A,A,A,A
12,match_12,H,H,H,H,H,H,H,H,H,...,D,A,A,A,A,A,A,A,A,A
13,match_13,H,H,H,D,D,D,A,A,A,...,A,H,H,H,D,D,D,A,A,A
14,match_14,H,D,A,H,D,A,H,D,A,...,A,H,D,A,H,D,A,H,D,A

In [3]:
import pandas as pd

def extract_column(file_path, column_name):
    # Load the data frame from the file
    df = pd.read_csv(file_path)

    # Extract the desired column
    extracted_col = df[column_name]

    # Return the extracted column
    return extracted_col

In [ ]:
extracted_col = extract_column('/path/to/file.csv', 'column_name')

In [4]:
# Extract the desired column
extracted_col = sample_space_file['pick_593185']
print(extracted_col)

0     H
1     H
2     D
3     H
4     D
5     H
6     H
7     D
8     H
9     A
10    H
11    H
12    A
13    D
14    D
Name: pick_593185, dtype: object

In [5]:
df = pd.read_csv('/content/drive/MyDrive/maGiK_15_assets/2nd_run/assets_12/results_df_assets_12.csv')

In [6]:
df

,Unnamed: 0,folder_path,file_name,column_name
0,0,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file1_concat.csv,pick_593185
1,1,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file1_concat.csv,pick_770323
2,2,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file1_concat.csv,pick_541645
3,3,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file1_concat.csv,pick_593175
4,4,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file1_concat.csv,pick_542375
...,...,...,...,...
60,60,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file9_concat.csv,pick_12754668
61,61,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file9_concat.csv,pick_12791037
62,62,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file9_concat.csv,pick_12791043
63,63,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file9_concat.csv,pick_12789588
64,64,/content/drive/MyDrive/maGiK_15_sample_space,df_magik15_file9_concat.csv,pick_13904849

In [7]:
import pandas as pd

def extract_picks(df):
    picks_list = df.loc[df['file_name'].str.contains('_file1_'), 'column_name'].tolist()
    return picks_list

In [8]:
picks_list = extract_picks(df)

In [10]:
picks_list
print(len(picks_list))

14

In [13]:
import pandas as pd

def extract_picks(df, picks_list):
    assets_12_picks = df[picks_list]
    return assets_12_picks

In [14]:


assets_12_picks = extract_picks(sample_space_file, picks_list)

print(assets_12_picks)

   pick_593185 pick_770323 pick_541645 pick_593175 pick_542375 pick_777680  \
0            H           H           H           H           H           H
1            H           H           H           H           H           H
2            D           D           D           D           D           D
3            H           D           H           H           H           D
4            D           D           H           D           H           D
5            H           H           H           H           H           H
6            H           H           D           H           D           D
7            D           D           D           D           D           D
8            H           H           D           H           A           D
9            A           A           A           A           A           A
10           H           H           A           H           A           H
11           H           H           A           H           A           A
12           A           D           A           D           A           A
13           D           D           A           D           A           A
14           D           D           D           H           A           A

   pick_718630 pick_718793 pick_719360 pick_595363 pick_601262 pick_600695  \
0            H           H           H           H           H           H
1            H           H           H           H           H           H
2            D           D           D           D           D           D
3            D           D           D           H           H           H
4            H           H           H           D           D           D
5            H           H           H           H           H           H
6            D           D           D           H           D           D
7            D           D           D           A           D           D
8            D           D           A           H           A           D
9            A           A           A           A           A           A
10           H           A           H           H           H           A
11           A           A           A           H           A           A
12           A           A           A           D           A           A
13           A           A           A           D           A           A
14           D           A           A           D           A           A

   pick_600532 pick_542212
0            H           H
1            H           H
2            D           D
3            H           H
4            D           H
5            H           H
6            D           D
7            D           D
8            D           A
9            A           A
10           H           H
11           A           A
12           A           A
13           A           A
14           D           D